### ISSUE TITLE
a bit "blocked" when running the program without opening a buffer

### ISSUE THREAD

**Issue by brunobord** [vamolessa/pepper#13]
Hello,

I've played around with `pepper`, and I was a little bit puzzled with the following course of actions:

I've launched the `pepper` executable without any "file" argument:

```sh
$ pepper
```

After that, it looks like it's impossible to add any text or anything (you can't switch to "insert" mode, for example). You can't even run the command `:save myfile.txt` because it throws an error message: `error:no buffer opened`.

It looks strange but I often open my text editor to type text *and thereafter* save it to a new file.
So far, I didn't see how to do that with pepper, but I may be wrong. The only solution I can think of right now is to know how you're going to name your file beforehand (either by doing a `touch myfile.txt` or launch pepper with `myfile.txt` as an argument.

Do you see any better way, so far?

**Comment by vamolessa** [comment]
Oh, that's because there's no buffer opened.
You can use the [`open <file-path>`](https://github.com/vamolessa/pepper/blob/master/rc/command_reference.md#open) command to open a buffer and then you can start editing it.

Maybe we could add a little help when there's no buffer opened. Or add the "use the 'open' command" tip to the `error:no buffer opened` message.

**Comment by vamolessa** [comment]
Gonna close it. If you need further help, please reopen.
