### ISSUE TITLE
Bindings reference wiki: `|` on markdown table!

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#30]
In [bindings reference](https://github.com/vamolessa/pepper/wiki/bindings#text-object):

> ** `<pipe>` is `|`. I had to write like this because of markdown table formatting.

You could actually do this:

```md
| keys |      action      |
| ---- | ---------------- |
| `\|` | Do something ... |
```

| keys |      action      |
| ---- | ---------------- |
| `\|` | Do something ... |

**Comment by vamolessa** [comment]
Oh, the wiki really does need an update.
Or maybe just removed since all of the info that is there was moved into help pages in the main repository (and inside the editor) here: https://github.com/vamolessa/pepper/tree/master/pepper/rc
I'll delete them for now to remove the redundancy and the source of outdated knowledge
