### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by NNBnh** [vamolessa/pepper#32]
Hello,

First of, thank you for making such a great code editor. I have try out many editor but this is the best one so far. Great UX, more minimal than Neovim and [Helix](https://helix-editor.com) but still have enough features out of the box unlike Kakoune.

Let's get to the main point:
- When will this project reach v1.0 release?
- Does it have a roadmap, a todo list for this project?
- If you already planned out the roadmap, could you publish it through multiple small issues then add those to [the repo's milestones](https://github.com/vamolessa/pepper/milestones)?

**Comment by vamolessa** [comment]
I'm glad you find it useful. Thanks!

So, what I'd like for v1.0 is basically fix issues and improve stability. Maybe one feature here and there (like https://github.com/vamolessa/pepper/issues/29#issuecomment-1059976820 for example).

But essentially pepper is "feature complete" for v1.0 as it's already my main code editor for almost a whole year and I'm quite happy with it.

After that, I'll put my main efforts on improving and maintaining its plugin interface in order to support more use-cases through extensions.

However, there are some issues that only exist as a `TODO` comment inside the code right now.
So I will transform those into proper issues for better tracking.

As for when we get there, that's hard to answer since I don't work fulltime on Pepper.
I'll explore the Milestone feature. Never used it before!

Thanks

**Comment by vamolessa** [comment]
I've created those missing issues and moved them together with some old ones to the new `v1.0` [milestone](https://github.com/vamolessa/pepper/milestone/1)!
